{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "golfs.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "golfs.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.kubernetesComponent }}
spec:
  parentRefs:
    - name: {{ include "golfs.fullname" . }}
  hostnames:
    {{- range .Values.gateway.hosts }}
    - {{ .host | quote }}
    {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /github.com
      backendRefs:
        - name: {{ include "golfs.fullname" . }}
          port: {{ .Values.publicService.port }}
{{- end }}
